<?xml version="1.0" encoding="UTF-8"?>
<!--                               -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns="urn:us:gov:dot:faa:weather:iesp:nwrx:1:0" name="AckRpt_wsdl" targetNamespace="urn:us:gov:dot:faa:weather:iesp:nwrx:1:0">
	<wsdl:types>
		<xsd:schema xmlns:ns="urn:us:gov:dot:faa:weather:iesp:nwrx:1:0" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="urn:us:gov:dot:faa:weather:iesp:nwrx:1:0">
			<xsd:include schemaLocation="wmscr.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="Request">
		<wsdl:part name="payload" element="AcknowledgeReportMessage"/>
	</wsdl:message>
	<wsdl:portType name="AckRpt">
		<wsdl:operation name="AckRpt">
			<wsdl:input message="Request"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="AckRptSOAP11Binding" type="AckRpt">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="AckRpt">
			<soap:operation soapAction="urn:AckRpt" style="document"/>
			<wsdl:input>
				<soap:body parts="payload" use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="AckRptSvc">
		<wsdl:port name="AckRptEndpoint" binding="AckRptSOAP11Binding">
			<soap:address location="http://0.0.0.0:60000/AckRpt/"/>
		</wsdl:port>
		<wsdl:port name="AckRptSecEndpoint" binding="AckRptSOAP11Binding">
			<soap:address location="https://0.0.0.0:60001/AckRpt/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
