<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fdpsgeneralmessagepub="us:gov:dot:faa:atm:enroute:services:generalmessagepub" xmlns:fdpsdata="us:gov:dot:faa:atm:enroute:entities:flightdata" name="enroute-general-message-data-publication-wsdl" targetNamespace="us:gov:dot:faa:atm:enroute:services:generalmessagepub">
	<wsdl:documentation>EnRoute General Message Publication</wsdl:documentation>
	<wsdl:types>
		<xs:schema>
			<xs:annotation>
				<xs:documentation>
					*******************************************************************
					EnRouteGeneralMessagePublicationDataModel.xsd contains the definitions of the data
					types used in this wsdl
					*******************************************************************
				</xs:documentation>
			</xs:annotation>
			<xs:import namespace="us:gov:dot:faa:atm:enroute:entities:flightdata" schemaLocation="EnRouteGeneralMessagePublicationDataModel.xsd"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="FdpsSubscriptionRequestMessage">
		<wsdl:part name="FdpsSubscriptionRequest" element="fdpsdata:FdpsGeneralMessagePublicationSubscriptionRequestElement">
	    </wsdl:part>
	</wsdl:message>
	<wsdl:message name="FdpsSubscriptionResponseMessage">
		<wsdl:part name="FdpsSubscriptionResponse" element="fdpsdata:FdpsGeneralMessagePublicationSubscriptionResponseElement">
	    </wsdl:part>
	</wsdl:message>
	<wsdl:message name="FdpsSubscriptionFaultMessage">
		<wsdl:part name="fdpssubscriptionfaultpayload" element="fdpsdata:FdpsGeneralMessagePublicationSubscriptionFaultElement">
	    </wsdl:part>
	</wsdl:message>
	<wsdl:portType name="FdpsGeneralMessageSubscriptionPortType">
		<wsdl:operation name="GetFdpsSubscription">
			<wsdl:input message="fdpsgeneralmessagepub:FdpsSubscriptionRequestMessage"/>
			<wsdl:output message="fdpsgeneralmessagepub:FdpsSubscriptionResponseMessage"/>
			<wsdl:fault name="FdpsSubscriptionFault" message="fdpsgeneralmessagepub:FdpsSubscriptionFaultMessage"> </wsdl:fault>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="FdpsGeneralMessageSubscriptionSOAPBinding" type="fdpsgeneralmessagepub:FdpsGeneralMessageSubscriptionPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="GetFdpsSubscription">
			<soap:operation soapAction="" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="FdpsSubscriptionFault">
				<soap:fault name="FdpsSubscriptionFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="EnrouteGeneralMessagePublication">
		<wsdl:port name="EnrouteGeneralMessagePublicationSoapOverHttp" binding="fdpsgeneralmessagepub:FdpsGeneralMessageSubscriptionSOAPBinding">
			<soap:address location="https://11.22.11.22:9000/EnrouteGeneralMessagePublication/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
