<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fdpsairspacedatapub="us:gov:dot:faa:atm:enroute:services:airspacedatapub" xmlns:fdpsdata="us:gov:dot:faa:atm:enroute:entities:flightdata" name="enroute-airspace-data-publication-wsdl" targetNamespace="us:gov:dot:faa:atm:enroute:services:airspacedatapub">
	<wsdl:documentation>EnRoute Airspace Data Publication</wsdl:documentation>
	<wsdl:types>
		<xs:schema>
			<xs:annotation>
				<xs:documentation>[
					*******************************************************************
					EnRouteAirspaceDataPublicationDataModel.xsd contains the definitions of the data
					types used in this wsdl
					*******************************************************************
				</xs:documentation>
			</xs:annotation>
			<xs:import namespace="us:gov:dot:faa:atm:enroute:entities:flightdata" schemaLocation="EnRouteAirspaceDataPublicationDataModel.xsd"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="FdpsSubscriptionRequestMessage">
		<wsdl:part name="FdpsSubscriptionRequest" element="fdpsdata:FdpsAirspaceDataSubscriptionRequestElement">
	    </wsdl:part>
	</wsdl:message>
	<wsdl:message name="FdpsSubscriptionResponseMessage">
		<wsdl:part name="FdpsSubscriptionResponse" element="fdpsdata:FdpsAirspaceDataSubscriptionResponseElement">
	    </wsdl:part>
	</wsdl:message>
	<wsdl:message name="FdpsSubscriptionFaultMessage">
		<wsdl:part name="fdpssubscriptionfaultpayload" element="fdpsdata:FdpsAirspaceDataSubscriptionFaultElement">
	    </wsdl:part>
	</wsdl:message>
	<wsdl:portType name="FdpsAirspaceSubscriptionPortType">
		<wsdl:operation name="GetFdpsSubscription">
			<wsdl:input message="fdpsairspacedatapub:FdpsSubscriptionRequestMessage"/>
			<wsdl:output message="fdpsairspacedatapub:FdpsSubscriptionResponseMessage"/>
			<wsdl:fault name="FdpsSubscriptionFault" message="fdpsairspacedatapub:FdpsSubscriptionFaultMessage"> </wsdl:fault>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="FdpsAirspaceSubscriptionSOAPBinding" type="fdpsairspacedatapub:FdpsAirspaceSubscriptionPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="GetFdpsSubscription">
			<soap:operation soapAction="" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="FdpsSubscriptionFault">
				<soap:fault name="FdpsSubscriptionFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="EnrouteAirspaceDataPublication">
		<wsdl:port name="EnrouteAirspaceDataPublicationSoapOverHttp" binding="fdpsairspacedatapub:FdpsAirspaceSubscriptionSOAPBinding">
			<soap:address location="https://11.22.11.22:9000/EnrouteAirspaceDataPublication/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
